name: Lint
on:
  pull_request:

jobs:
  lint:
    name: Lint GHA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: make -f lint.Makefile lint
